//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.3
//     from Assets/Input/GameInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameInput"",
    ""maps"": [
        {
            ""name"": ""BaseGameplay"",
            ""id"": ""243adb45-9057-48c5-ac8c-586ec1fb74ea"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""4dfbc952-cb33-46f1-99d4-91668d3fdd6f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""GamepadDirection"",
                    ""type"": ""Value"",
                    ""id"": ""ddf265c0-91dc-45d5-9f1e-56d5f81a5361"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MousePosition"",
                    ""type"": ""Value"",
                    ""id"": ""c6c8e33b-f122-4ea8-8c55-55c8b9a1fa61"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""FirePrimary"",
                    ""type"": ""Button"",
                    ""id"": ""f8a3d247-93d5-4ed2-947a-e31d3bec3c81"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FireSecondary"",
                    ""type"": ""Button"",
                    ""id"": ""f8f558dd-66e7-465c-bcd1-881632efeadd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenShipMenu"",
                    ""type"": ""Button"",
                    ""id"": ""6eb2e277-ba14-4ab5-b929-542b3b148a62"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectWeaponSlot1"",
                    ""type"": ""Button"",
                    ""id"": ""c60b7956-0681-4b98-9bb6-8ce4f401bea7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectWeaponSlot2"",
                    ""type"": ""Button"",
                    ""id"": ""65ceeeb0-0102-4cd9-9e0a-20b76ebb99b2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectWeaponSlot3"",
                    ""type"": ""Button"",
                    ""id"": ""d6573ad0-01dc-4022-817a-bf5570ac1d39"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectWeaponSlot4"",
                    ""type"": ""Button"",
                    ""id"": ""b9aa3c06-e5c9-45e3-ab59-cdec327c9728"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CycleWeaponSlotForward"",
                    ""type"": ""Button"",
                    ""id"": ""3066aec8-639a-4da5-b21f-983e89252a78"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CycleWeaponSlotBackward"",
                    ""type"": ""Button"",
                    ""id"": ""4981fde5-7352-471b-a578-9d01b57c97a1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Boost"",
                    ""type"": ""Button"",
                    ""id"": ""94e72b81-da9a-494e-96bc-daeadd5a95d2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""IncDecWeaponSlot"",
                    ""type"": ""Value"",
                    ""id"": ""48ed32f6-66ab-468b-bc90-606c99d4a116"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""9a14c5d8-1623-45a5-b781-8f8f2a09bd79"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""57b5579a-beac-4a31-aa63-3236c9f82848"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""7a3c0cf6-7f5f-4955-913d-874ddd2b6cf8"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""1d6dfa0e-d366-4733-a138-1f9459245ffb"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""2b4b1b5c-418b-483d-8a4f-dbcd06418e07"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""5765d8d4-730b-42db-aa35-9df5efa18cf5"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone"",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1ddeb859-9508-4662-8b17-45ff164a3592"",
                    ""path"": ""<Pointer>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""MousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0d709e67-0042-4fcb-9dd5-bd46bffb3727"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""FirePrimary"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""16a21bd0-6338-424c-bb86-bc7c84f76d0b"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""FirePrimary"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4fd6c712-fe14-46a5-bb94-9e1d84ce46ed"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""FireSecondary"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e44a35d0-1abd-48c6-bbc2-988339aefe06"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""FireSecondary"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2ea653ef-2e04-48a8-a28e-7c163ad0fc1e"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""OpenShipMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""64c4b4cc-54d8-419e-bffc-6924cbf4959a"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""OpenShipMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""244175ab-1921-493c-ad05-9fbf4c276452"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""SelectWeaponSlot1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0bbe8ffa-96e8-4ea9-9b74-3cd9e964186a"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""SelectWeaponSlot2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""66d938f9-56fd-47d6-bf77-d4ccc9753c5c"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectWeaponSlot3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""15320c13-fd2c-41b7-abc4-d5042b7c2986"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectWeaponSlot4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6924853f-952a-47d4-b633-a8babafdfcb5"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""CycleWeaponSlotForward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""03d76fd7-6324-4984-aacb-2d520f3693ff"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""CycleWeaponSlotBackward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""10d23cce-1e4f-421c-8d1c-23f815cb533a"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Boost"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""12e3c12f-28a8-4b79-852f-eb4502a0d36e"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Boost"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""956de39c-6eb0-4e63-bbb6-b67550882b50"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone"",
                    ""groups"": ""Gamepad"",
                    ""action"": ""GamepadDirection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""cd38c5a8-f4a0-459b-9387-1d5760ad42ed"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""IncDecWeaponSlot"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""fe5c9f65-f7b0-47f3-9894-3446be768601"",
                    ""path"": ""<Mouse>/scroll/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""IncDecWeaponSlot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""08143fca-04d2-4038-8e5f-27cc24efc190"",
                    ""path"": ""<Mouse>/scroll/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""IncDecWeaponSlot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""PlayershipMenu"",
            ""id"": ""c0d88006-03e3-42a9-9241-e3f87984f352"",
            ""actions"": [
                {
                    ""name"": ""CloseShipMenu"",
                    ""type"": ""Button"",
                    ""id"": ""af4042bb-3743-4dae-a155-111d175c01f5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2a40132b-f2fc-4ee1-9ba6-a0fcfc52208c"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""CloseShipMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""078ca752-00ea-4b20-a9c3-574dfe37049a"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""CloseShipMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard&Mouse"",
            ""bindingGroup"": ""Keyboard&Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // BaseGameplay
        m_BaseGameplay = asset.FindActionMap("BaseGameplay", throwIfNotFound: true);
        m_BaseGameplay_Movement = m_BaseGameplay.FindAction("Movement", throwIfNotFound: true);
        m_BaseGameplay_GamepadDirection = m_BaseGameplay.FindAction("GamepadDirection", throwIfNotFound: true);
        m_BaseGameplay_MousePosition = m_BaseGameplay.FindAction("MousePosition", throwIfNotFound: true);
        m_BaseGameplay_FirePrimary = m_BaseGameplay.FindAction("FirePrimary", throwIfNotFound: true);
        m_BaseGameplay_FireSecondary = m_BaseGameplay.FindAction("FireSecondary", throwIfNotFound: true);
        m_BaseGameplay_OpenShipMenu = m_BaseGameplay.FindAction("OpenShipMenu", throwIfNotFound: true);
        m_BaseGameplay_SelectWeaponSlot1 = m_BaseGameplay.FindAction("SelectWeaponSlot1", throwIfNotFound: true);
        m_BaseGameplay_SelectWeaponSlot2 = m_BaseGameplay.FindAction("SelectWeaponSlot2", throwIfNotFound: true);
        m_BaseGameplay_SelectWeaponSlot3 = m_BaseGameplay.FindAction("SelectWeaponSlot3", throwIfNotFound: true);
        m_BaseGameplay_SelectWeaponSlot4 = m_BaseGameplay.FindAction("SelectWeaponSlot4", throwIfNotFound: true);
        m_BaseGameplay_CycleWeaponSlotForward = m_BaseGameplay.FindAction("CycleWeaponSlotForward", throwIfNotFound: true);
        m_BaseGameplay_CycleWeaponSlotBackward = m_BaseGameplay.FindAction("CycleWeaponSlotBackward", throwIfNotFound: true);
        m_BaseGameplay_Boost = m_BaseGameplay.FindAction("Boost", throwIfNotFound: true);
        m_BaseGameplay_IncDecWeaponSlot = m_BaseGameplay.FindAction("IncDecWeaponSlot", throwIfNotFound: true);
        // PlayershipMenu
        m_PlayershipMenu = asset.FindActionMap("PlayershipMenu", throwIfNotFound: true);
        m_PlayershipMenu_CloseShipMenu = m_PlayershipMenu.FindAction("CloseShipMenu", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // BaseGameplay
    private readonly InputActionMap m_BaseGameplay;
    private IBaseGameplayActions m_BaseGameplayActionsCallbackInterface;
    private readonly InputAction m_BaseGameplay_Movement;
    private readonly InputAction m_BaseGameplay_GamepadDirection;
    private readonly InputAction m_BaseGameplay_MousePosition;
    private readonly InputAction m_BaseGameplay_FirePrimary;
    private readonly InputAction m_BaseGameplay_FireSecondary;
    private readonly InputAction m_BaseGameplay_OpenShipMenu;
    private readonly InputAction m_BaseGameplay_SelectWeaponSlot1;
    private readonly InputAction m_BaseGameplay_SelectWeaponSlot2;
    private readonly InputAction m_BaseGameplay_SelectWeaponSlot3;
    private readonly InputAction m_BaseGameplay_SelectWeaponSlot4;
    private readonly InputAction m_BaseGameplay_CycleWeaponSlotForward;
    private readonly InputAction m_BaseGameplay_CycleWeaponSlotBackward;
    private readonly InputAction m_BaseGameplay_Boost;
    private readonly InputAction m_BaseGameplay_IncDecWeaponSlot;
    public struct BaseGameplayActions
    {
        private @GameInput m_Wrapper;
        public BaseGameplayActions(@GameInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_BaseGameplay_Movement;
        public InputAction @GamepadDirection => m_Wrapper.m_BaseGameplay_GamepadDirection;
        public InputAction @MousePosition => m_Wrapper.m_BaseGameplay_MousePosition;
        public InputAction @FirePrimary => m_Wrapper.m_BaseGameplay_FirePrimary;
        public InputAction @FireSecondary => m_Wrapper.m_BaseGameplay_FireSecondary;
        public InputAction @OpenShipMenu => m_Wrapper.m_BaseGameplay_OpenShipMenu;
        public InputAction @SelectWeaponSlot1 => m_Wrapper.m_BaseGameplay_SelectWeaponSlot1;
        public InputAction @SelectWeaponSlot2 => m_Wrapper.m_BaseGameplay_SelectWeaponSlot2;
        public InputAction @SelectWeaponSlot3 => m_Wrapper.m_BaseGameplay_SelectWeaponSlot3;
        public InputAction @SelectWeaponSlot4 => m_Wrapper.m_BaseGameplay_SelectWeaponSlot4;
        public InputAction @CycleWeaponSlotForward => m_Wrapper.m_BaseGameplay_CycleWeaponSlotForward;
        public InputAction @CycleWeaponSlotBackward => m_Wrapper.m_BaseGameplay_CycleWeaponSlotBackward;
        public InputAction @Boost => m_Wrapper.m_BaseGameplay_Boost;
        public InputAction @IncDecWeaponSlot => m_Wrapper.m_BaseGameplay_IncDecWeaponSlot;
        public InputActionMap Get() { return m_Wrapper.m_BaseGameplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BaseGameplayActions set) { return set.Get(); }
        public void SetCallbacks(IBaseGameplayActions instance)
        {
            if (m_Wrapper.m_BaseGameplayActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_BaseGameplayActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_BaseGameplayActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_BaseGameplayActionsCallbackInterface.OnMovement;
                @GamepadDirection.started -= m_Wrapper.m_BaseGameplayActionsCallbackInterface.OnGamepadDirection;
                @GamepadDirection.performed -= m_Wrapper.m_BaseGameplayActionsCallbackInterface.OnGamepadDirection;
                @GamepadDirection.canceled -= m_Wrapper.m_BaseGameplayActionsCallbackInterface.OnGamepadDirection;
                @MousePosition.started -= m_Wrapper.m_BaseGameplayActionsCallbackInterface.OnMousePosition;
                @MousePosition.performed -= m_Wrapper.m_BaseGameplayActionsCallbackInterface.OnMousePosition;
                @MousePosition.canceled -= m_Wrapper.m_BaseGameplayActionsCallbackInterface.OnMousePosition;
                @FirePrimary.started -= m_Wrapper.m_BaseGameplayActionsCallbackInterface.OnFirePrimary;
                @FirePrimary.performed -= m_Wrapper.m_BaseGameplayActionsCallbackInterface.OnFirePrimary;
                @FirePrimary.canceled -= m_Wrapper.m_BaseGameplayActionsCallbackInterface.OnFirePrimary;
                @FireSecondary.started -= m_Wrapper.m_BaseGameplayActionsCallbackInterface.OnFireSecondary;
                @FireSecondary.performed -= m_Wrapper.m_BaseGameplayActionsCallbackInterface.OnFireSecondary;
                @FireSecondary.canceled -= m_Wrapper.m_BaseGameplayActionsCallbackInterface.OnFireSecondary;
                @OpenShipMenu.started -= m_Wrapper.m_BaseGameplayActionsCallbackInterface.OnOpenShipMenu;
                @OpenShipMenu.performed -= m_Wrapper.m_BaseGameplayActionsCallbackInterface.OnOpenShipMenu;
                @OpenShipMenu.canceled -= m_Wrapper.m_BaseGameplayActionsCallbackInterface.OnOpenShipMenu;
                @SelectWeaponSlot1.started -= m_Wrapper.m_BaseGameplayActionsCallbackInterface.OnSelectWeaponSlot1;
                @SelectWeaponSlot1.performed -= m_Wrapper.m_BaseGameplayActionsCallbackInterface.OnSelectWeaponSlot1;
                @SelectWeaponSlot1.canceled -= m_Wrapper.m_BaseGameplayActionsCallbackInterface.OnSelectWeaponSlot1;
                @SelectWeaponSlot2.started -= m_Wrapper.m_BaseGameplayActionsCallbackInterface.OnSelectWeaponSlot2;
                @SelectWeaponSlot2.performed -= m_Wrapper.m_BaseGameplayActionsCallbackInterface.OnSelectWeaponSlot2;
                @SelectWeaponSlot2.canceled -= m_Wrapper.m_BaseGameplayActionsCallbackInterface.OnSelectWeaponSlot2;
                @SelectWeaponSlot3.started -= m_Wrapper.m_BaseGameplayActionsCallbackInterface.OnSelectWeaponSlot3;
                @SelectWeaponSlot3.performed -= m_Wrapper.m_BaseGameplayActionsCallbackInterface.OnSelectWeaponSlot3;
                @SelectWeaponSlot3.canceled -= m_Wrapper.m_BaseGameplayActionsCallbackInterface.OnSelectWeaponSlot3;
                @SelectWeaponSlot4.started -= m_Wrapper.m_BaseGameplayActionsCallbackInterface.OnSelectWeaponSlot4;
                @SelectWeaponSlot4.performed -= m_Wrapper.m_BaseGameplayActionsCallbackInterface.OnSelectWeaponSlot4;
                @SelectWeaponSlot4.canceled -= m_Wrapper.m_BaseGameplayActionsCallbackInterface.OnSelectWeaponSlot4;
                @CycleWeaponSlotForward.started -= m_Wrapper.m_BaseGameplayActionsCallbackInterface.OnCycleWeaponSlotForward;
                @CycleWeaponSlotForward.performed -= m_Wrapper.m_BaseGameplayActionsCallbackInterface.OnCycleWeaponSlotForward;
                @CycleWeaponSlotForward.canceled -= m_Wrapper.m_BaseGameplayActionsCallbackInterface.OnCycleWeaponSlotForward;
                @CycleWeaponSlotBackward.started -= m_Wrapper.m_BaseGameplayActionsCallbackInterface.OnCycleWeaponSlotBackward;
                @CycleWeaponSlotBackward.performed -= m_Wrapper.m_BaseGameplayActionsCallbackInterface.OnCycleWeaponSlotBackward;
                @CycleWeaponSlotBackward.canceled -= m_Wrapper.m_BaseGameplayActionsCallbackInterface.OnCycleWeaponSlotBackward;
                @Boost.started -= m_Wrapper.m_BaseGameplayActionsCallbackInterface.OnBoost;
                @Boost.performed -= m_Wrapper.m_BaseGameplayActionsCallbackInterface.OnBoost;
                @Boost.canceled -= m_Wrapper.m_BaseGameplayActionsCallbackInterface.OnBoost;
                @IncDecWeaponSlot.started -= m_Wrapper.m_BaseGameplayActionsCallbackInterface.OnIncDecWeaponSlot;
                @IncDecWeaponSlot.performed -= m_Wrapper.m_BaseGameplayActionsCallbackInterface.OnIncDecWeaponSlot;
                @IncDecWeaponSlot.canceled -= m_Wrapper.m_BaseGameplayActionsCallbackInterface.OnIncDecWeaponSlot;
            }
            m_Wrapper.m_BaseGameplayActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @GamepadDirection.started += instance.OnGamepadDirection;
                @GamepadDirection.performed += instance.OnGamepadDirection;
                @GamepadDirection.canceled += instance.OnGamepadDirection;
                @MousePosition.started += instance.OnMousePosition;
                @MousePosition.performed += instance.OnMousePosition;
                @MousePosition.canceled += instance.OnMousePosition;
                @FirePrimary.started += instance.OnFirePrimary;
                @FirePrimary.performed += instance.OnFirePrimary;
                @FirePrimary.canceled += instance.OnFirePrimary;
                @FireSecondary.started += instance.OnFireSecondary;
                @FireSecondary.performed += instance.OnFireSecondary;
                @FireSecondary.canceled += instance.OnFireSecondary;
                @OpenShipMenu.started += instance.OnOpenShipMenu;
                @OpenShipMenu.performed += instance.OnOpenShipMenu;
                @OpenShipMenu.canceled += instance.OnOpenShipMenu;
                @SelectWeaponSlot1.started += instance.OnSelectWeaponSlot1;
                @SelectWeaponSlot1.performed += instance.OnSelectWeaponSlot1;
                @SelectWeaponSlot1.canceled += instance.OnSelectWeaponSlot1;
                @SelectWeaponSlot2.started += instance.OnSelectWeaponSlot2;
                @SelectWeaponSlot2.performed += instance.OnSelectWeaponSlot2;
                @SelectWeaponSlot2.canceled += instance.OnSelectWeaponSlot2;
                @SelectWeaponSlot3.started += instance.OnSelectWeaponSlot3;
                @SelectWeaponSlot3.performed += instance.OnSelectWeaponSlot3;
                @SelectWeaponSlot3.canceled += instance.OnSelectWeaponSlot3;
                @SelectWeaponSlot4.started += instance.OnSelectWeaponSlot4;
                @SelectWeaponSlot4.performed += instance.OnSelectWeaponSlot4;
                @SelectWeaponSlot4.canceled += instance.OnSelectWeaponSlot4;
                @CycleWeaponSlotForward.started += instance.OnCycleWeaponSlotForward;
                @CycleWeaponSlotForward.performed += instance.OnCycleWeaponSlotForward;
                @CycleWeaponSlotForward.canceled += instance.OnCycleWeaponSlotForward;
                @CycleWeaponSlotBackward.started += instance.OnCycleWeaponSlotBackward;
                @CycleWeaponSlotBackward.performed += instance.OnCycleWeaponSlotBackward;
                @CycleWeaponSlotBackward.canceled += instance.OnCycleWeaponSlotBackward;
                @Boost.started += instance.OnBoost;
                @Boost.performed += instance.OnBoost;
                @Boost.canceled += instance.OnBoost;
                @IncDecWeaponSlot.started += instance.OnIncDecWeaponSlot;
                @IncDecWeaponSlot.performed += instance.OnIncDecWeaponSlot;
                @IncDecWeaponSlot.canceled += instance.OnIncDecWeaponSlot;
            }
        }
    }
    public BaseGameplayActions @BaseGameplay => new BaseGameplayActions(this);

    // PlayershipMenu
    private readonly InputActionMap m_PlayershipMenu;
    private IPlayershipMenuActions m_PlayershipMenuActionsCallbackInterface;
    private readonly InputAction m_PlayershipMenu_CloseShipMenu;
    public struct PlayershipMenuActions
    {
        private @GameInput m_Wrapper;
        public PlayershipMenuActions(@GameInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @CloseShipMenu => m_Wrapper.m_PlayershipMenu_CloseShipMenu;
        public InputActionMap Get() { return m_Wrapper.m_PlayershipMenu; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayershipMenuActions set) { return set.Get(); }
        public void SetCallbacks(IPlayershipMenuActions instance)
        {
            if (m_Wrapper.m_PlayershipMenuActionsCallbackInterface != null)
            {
                @CloseShipMenu.started -= m_Wrapper.m_PlayershipMenuActionsCallbackInterface.OnCloseShipMenu;
                @CloseShipMenu.performed -= m_Wrapper.m_PlayershipMenuActionsCallbackInterface.OnCloseShipMenu;
                @CloseShipMenu.canceled -= m_Wrapper.m_PlayershipMenuActionsCallbackInterface.OnCloseShipMenu;
            }
            m_Wrapper.m_PlayershipMenuActionsCallbackInterface = instance;
            if (instance != null)
            {
                @CloseShipMenu.started += instance.OnCloseShipMenu;
                @CloseShipMenu.performed += instance.OnCloseShipMenu;
                @CloseShipMenu.canceled += instance.OnCloseShipMenu;
            }
        }
    }
    public PlayershipMenuActions @PlayershipMenu => new PlayershipMenuActions(this);
    private int m_KeyboardMouseSchemeIndex = -1;
    public InputControlScheme KeyboardMouseScheme
    {
        get
        {
            if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard&Mouse");
            return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    public interface IBaseGameplayActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnGamepadDirection(InputAction.CallbackContext context);
        void OnMousePosition(InputAction.CallbackContext context);
        void OnFirePrimary(InputAction.CallbackContext context);
        void OnFireSecondary(InputAction.CallbackContext context);
        void OnOpenShipMenu(InputAction.CallbackContext context);
        void OnSelectWeaponSlot1(InputAction.CallbackContext context);
        void OnSelectWeaponSlot2(InputAction.CallbackContext context);
        void OnSelectWeaponSlot3(InputAction.CallbackContext context);
        void OnSelectWeaponSlot4(InputAction.CallbackContext context);
        void OnCycleWeaponSlotForward(InputAction.CallbackContext context);
        void OnCycleWeaponSlotBackward(InputAction.CallbackContext context);
        void OnBoost(InputAction.CallbackContext context);
        void OnIncDecWeaponSlot(InputAction.CallbackContext context);
    }
    public interface IPlayershipMenuActions
    {
        void OnCloseShipMenu(InputAction.CallbackContext context);
    }
}
